version: '3.4'

services:
  bcfinaltheatermanagementbff:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "30000:80"

  fakemoviecatalogsvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

